import { cache } from "react";
import type {
  WorkoutFilterOptions,
  WorkoutProgram,
} from "@/components/workouts/types";

const LEVELS = ["Beginner", "Intermediate", "Advanced"];
const GOALS = ["Fat Loss", "Strength", "Muscle Gain", "Conditioning", "Mobility"];
const EQUIPMENT = ["Full Gym", "At Home", "Bodyweight", "Dumbbells"];
const DURATIONS = [30, 45, 60, 75];

const CURATED_WORKOUT_PROGRAMS: WorkoutProgram[] = [
  {
    id: "beginner-full-gym-fat-loss-30",
    title: "Beginner Full Gym Fat Loss Circuit",
    description:
      "A simple full-body gym circuit that combines machines, light resistance, and steady pacing to build consistency and support healthy fat loss.",
    level: "Beginner",
    goal: "Fat Loss",
    equipment: "Full Gym",
    duration: 30,
    programLength: 4,
    totalExercises: 18,
    recommendedFor: "New gym members who want short, structured sessions.",
  },
  {
    id: "beginner-at-home-fat-loss-30",
    title: "Beginner At Home Fat Loss Plan",
    description:
      "A low-impact home routine with approachable strength intervals and cardio finishers designed for sustainable weekly progress.",
    level: "Beginner",
    goal: "Fat Loss",
    equipment: "At Home",
    duration: 30,
    programLength: 4,
    totalExercises: 16,
    recommendedFor: "Beginners training at home with limited space.",
  },
  {
    id: "beginner-bodyweight-fat-loss-45",
    title: "Beginner Bodyweight Fat Loss Foundation",
    description:
      "A bodyweight plan focused on basic movement patterns, controlled tempo, and moderate conditioning without equipment.",
    level: "Beginner",
    goal: "Fat Loss",
    equipment: "Bodyweight",
    duration: 45,
    programLength: 5,
    totalExercises: 20,
    recommendedFor: "Users who prefer equipment-free training.",
  },
  {
    id: "beginner-dumbbells-fat-loss-45",
    title: "Beginner Dumbbell Fat Loss Program",
    description:
      "A beginner-friendly dumbbell routine pairing strength sets with brisk conditioning blocks for practical calorie expenditure.",
    level: "Beginner",
    goal: "Fat Loss",
    equipment: "Dumbbells",
    duration: 45,
    programLength: 6,
    totalExercises: 22,
    recommendedFor: "Home trainees with a light to moderate dumbbell set.",
  },
  {
    id: "beginner-full-gym-strength-45",
    title: "Beginner Full Gym Strength Plan",
    description:
      "A machine-supported strength program that teaches safe movement patterns before progressing to heavier compound lifts.",
    level: "Beginner",
    goal: "Strength",
    equipment: "Full Gym",
    duration: 45,
    programLength: 6,
    totalExercises: 24,
    recommendedFor: "Beginners learning structured strength training.",
  },
  {
    id: "beginner-at-home-strength-45",
    title: "Beginner At Home Strength Builder",
    description:
      "A home strength plan using controlled reps, household-friendly movements, and clear progression targets.",
    level: "Beginner",
    goal: "Strength",
    equipment: "At Home",
    duration: 45,
    programLength: 5,
    totalExercises: 20,
    recommendedFor: "Users starting a strength routine outside the gym.",
  },
  {
    id: "beginner-bodyweight-strength-30",
    title: "Beginner Bodyweight Strength Plan",
    description:
      "A foundational bodyweight program that builds strength through squats, push patterns, hinges, core work, and mobility.",
    level: "Beginner",
    goal: "Strength",
    equipment: "Bodyweight",
    duration: 30,
    programLength: 4,
    totalExercises: 18,
    recommendedFor: "New trainees who want to master basic movements.",
  },
  {
    id: "beginner-dumbbells-strength-45",
    title: "Beginner Dumbbell Strength Program",
    description:
      "A balanced dumbbell plan for building strength with simple progressions and repeatable weekly sessions.",
    level: "Beginner",
    goal: "Strength",
    equipment: "Dumbbells",
    duration: 45,
    programLength: 6,
    totalExercises: 24,
    recommendedFor: "Beginners with adjustable or fixed dumbbells.",
  },
  {
    id: "beginner-full-gym-muscle-gain-60",
    title: "Beginner Full Gym Muscle Gain Program",
    description:
      "A gym-based hypertrophy plan with machine and free-weight exercises arranged for smooth learning and steady volume.",
    level: "Beginner",
    goal: "Muscle Gain",
    equipment: "Full Gym",
    duration: 60,
    programLength: 8,
    totalExercises: 32,
    recommendedFor: "Beginners who want a clear introduction to muscle building.",
  },
  {
    id: "beginner-dumbbells-muscle-gain-45",
    title: "Beginner Dumbbell Muscle Gain Plan",
    description:
      "A practical dumbbell hypertrophy plan targeting the full body with manageable sets, reps, and rest periods.",
    level: "Beginner",
    goal: "Muscle Gain",
    equipment: "Dumbbells",
    duration: 45,
    programLength: 8,
    totalExercises: 28,
    recommendedFor: "Users building muscle with simple home equipment.",
  },
  {
    id: "beginner-bodyweight-conditioning-30",
    title: "Beginner Bodyweight Conditioning Plan",
    description:
      "A low-barrier conditioning routine using bodyweight intervals, core work, and recovery-focused pacing.",
    level: "Beginner",
    goal: "Conditioning",
    equipment: "Bodyweight",
    duration: 30,
    programLength: 4,
    totalExercises: 16,
    recommendedFor: "Beginners improving stamina without equipment.",
  },
  {
    id: "beginner-at-home-conditioning-45",
    title: "Beginner At Home Conditioning Program",
    description:
      "A home-friendly conditioning plan that blends low-impact cardio, strength endurance, and mobility resets.",
    level: "Beginner",
    goal: "Conditioning",
    equipment: "At Home",
    duration: 45,
    programLength: 5,
    totalExercises: 22,
    recommendedFor: "Users who want better fitness with minimal setup.",
  },
  {
    id: "beginner-bodyweight-mobility-30",
    title: "Beginner Bodyweight Mobility Plan",
    description:
      "A gentle mobility routine designed to improve joint range, posture, and movement confidence with no equipment.",
    level: "Beginner",
    goal: "Mobility",
    equipment: "Bodyweight",
    duration: 30,
    programLength: 4,
    totalExercises: 18,
    recommendedFor: "Beginners who need a sustainable mobility habit.",
  },
  {
    id: "beginner-at-home-mobility-30",
    title: "Beginner At Home Mobility Routine",
    description:
      "A short guided routine for hips, shoulders, spine, and ankles that fits easily into a weekly home schedule.",
    level: "Beginner",
    goal: "Mobility",
    equipment: "At Home",
    duration: 30,
    programLength: 4,
    totalExercises: 16,
    recommendedFor: "Users prioritizing flexibility and daily movement quality.",
  },
  {
    id: "beginner-full-gym-conditioning-45",
    title: "Beginner Full Gym Conditioning Program",
    description:
      "A gym conditioning plan using cardio machines, light resistance circuits, and simple performance benchmarks.",
    level: "Beginner",
    goal: "Conditioning",
    equipment: "Full Gym",
    duration: 45,
    programLength: 5,
    totalExercises: 20,
    recommendedFor: "New gym members building aerobic capacity.",
  },
  {
    id: "beginner-dumbbells-mobility-30",
    title: "Beginner Dumbbell Mobility Support Plan",
    description:
      "A mobility-focused plan using light dumbbells for controlled range, stability, and posture-friendly strength.",
    level: "Beginner",
    goal: "Mobility",
    equipment: "Dumbbells",
    duration: 30,
    programLength: 4,
    totalExercises: 18,
    recommendedFor: "Users who want mobility with light strength support.",
  },
  {
    id: "intermediate-full-gym-fat-loss-60",
    title: "Intermediate Full Gym Fat Loss Program",
    description:
      "A structured gym plan combining strength supersets, cardio intervals, and planned recovery for fat loss progress.",
    level: "Intermediate",
    goal: "Fat Loss",
    equipment: "Full Gym",
    duration: 60,
    programLength: 8,
    totalExercises: 36,
    recommendedFor: "Consistent gym users ready for higher weekly workload.",
  },
  {
    id: "intermediate-at-home-fat-loss-45",
    title: "Intermediate At Home Fat Loss Plan",
    description:
      "A focused home plan using tempo strength work and conditioning intervals to support body composition goals.",
    level: "Intermediate",
    goal: "Fat Loss",
    equipment: "At Home",
    duration: 45,
    programLength: 6,
    totalExercises: 28,
    recommendedFor: "Home trainees with a regular training routine.",
  },
  {
    id: "intermediate-bodyweight-fat-loss-45",
    title: "Intermediate Bodyweight Fat Loss Circuit",
    description:
      "A bodyweight circuit program with progressive density, core work, and movement variety for efficient sessions.",
    level: "Intermediate",
    goal: "Fat Loss",
    equipment: "Bodyweight",
    duration: 45,
    programLength: 6,
    totalExercises: 30,
    recommendedFor: "Users who want challenging equipment-free fat loss work.",
  },
  {
    id: "intermediate-dumbbells-fat-loss-60",
    title: "Intermediate Dumbbell Fat Loss Program",
    description:
      "A dumbbell-based plan that pairs compound lifts with conditioning finishers for a strong metabolic stimulus.",
    level: "Intermediate",
    goal: "Fat Loss",
    equipment: "Dumbbells",
    duration: 60,
    programLength: 8,
    totalExercises: 34,
    recommendedFor: "Trainees who want efficient sessions with dumbbells.",
  },
  {
    id: "intermediate-full-gym-strength-60",
    title: "Intermediate Full Gym Strength Program",
    description:
      "A progressive strength plan built around compound lifts, accessory work, and weekly performance tracking.",
    level: "Intermediate",
    goal: "Strength",
    equipment: "Full Gym",
    duration: 60,
    programLength: 10,
    totalExercises: 40,
    recommendedFor: "Gym users building measurable strength.",
  },
  {
    id: "intermediate-dumbbells-strength-60",
    title: "Intermediate Dumbbell Strength Plan",
    description:
      "A focused dumbbell strength program using unilateral work, controlled tempo, and progressive overload.",
    level: "Intermediate",
    goal: "Strength",
    equipment: "Dumbbells",
    duration: 60,
    programLength: 8,
    totalExercises: 34,
    recommendedFor: "Trainees who train outside a full gym but want strength gains.",
  },
  {
    id: "intermediate-bodyweight-strength-45",
    title: "Intermediate Bodyweight Strength Program",
    description:
      "A calisthenics-inspired plan emphasizing push, pull, squat, hinge, and core progressions.",
    level: "Intermediate",
    goal: "Strength",
    equipment: "Bodyweight",
    duration: 45,
    programLength: 8,
    totalExercises: 32,
    recommendedFor: "Users who want strength without traditional equipment.",
  },
  {
    id: "intermediate-full-gym-muscle-gain-60",
    title: "Intermediate Full Gym Muscle Gain Program",
    description:
      "A balanced hypertrophy plan using compound lifts, machines, and accessories for weekly muscle-building volume.",
    level: "Intermediate",
    goal: "Muscle Gain",
    equipment: "Full Gym",
    duration: 60,
    programLength: 10,
    totalExercises: 42,
    recommendedFor: "Gym members ready for structured hypertrophy training.",
  },
  {
    id: "intermediate-full-gym-muscle-gain-75",
    title: "Intermediate Full Gym Hypertrophy Plan",
    description:
      "A longer hypertrophy plan with dedicated upper, lower, and accessory sessions for progressive muscle gain.",
    level: "Intermediate",
    goal: "Muscle Gain",
    equipment: "Full Gym",
    duration: 75,
    programLength: 12,
    totalExercises: 48,
    recommendedFor: "Trainees who can commit to longer gym sessions.",
  },
  {
    id: "intermediate-dumbbells-muscle-gain-60",
    title: "Intermediate Dumbbell Muscle Gain Program",
    description:
      "A dumbbell hypertrophy program using high-quality volume, unilateral exercises, and clear progression targets.",
    level: "Intermediate",
    goal: "Muscle Gain",
    equipment: "Dumbbells",
    duration: 60,
    programLength: 10,
    totalExercises: 40,
    recommendedFor: "Home or studio trainees focused on muscle growth.",
  },
  {
    id: "intermediate-full-gym-conditioning-60",
    title: "Intermediate Full Gym Conditioning Program",
    description:
      "A gym conditioning plan with intervals, loaded carries, circuits, and recovery weeks for durable fitness.",
    level: "Intermediate",
    goal: "Conditioning",
    equipment: "Full Gym",
    duration: 60,
    programLength: 8,
    totalExercises: 36,
    recommendedFor: "Users improving work capacity and cardio fitness.",
  },
  {
    id: "intermediate-bodyweight-conditioning-45",
    title: "Intermediate Bodyweight Conditioning Plan",
    description:
      "A bodyweight conditioning program using timed intervals, core stability, and progressive session density.",
    level: "Intermediate",
    goal: "Conditioning",
    equipment: "Bodyweight",
    duration: 45,
    programLength: 6,
    totalExercises: 30,
    recommendedFor: "Users who want portable conditioning sessions.",
  },
  {
    id: "intermediate-dumbbells-conditioning-45",
    title: "Intermediate Dumbbell Conditioning Program",
    description:
      "A dumbbell conditioning plan combining strength endurance, carries, complexes, and short rest periods.",
    level: "Intermediate",
    goal: "Conditioning",
    equipment: "Dumbbells",
    duration: 45,
    programLength: 6,
    totalExercises: 32,
    recommendedFor: "Trainees who enjoy compact, high-output workouts.",
  },
  {
    id: "intermediate-at-home-mobility-45",
    title: "Intermediate At Home Mobility Plan",
    description:
      "A progressive mobility plan for hips, shoulders, spine, and ankles with stability work included.",
    level: "Intermediate",
    goal: "Mobility",
    equipment: "At Home",
    duration: 45,
    programLength: 6,
    totalExercises: 28,
    recommendedFor: "Users who want better range of motion and posture.",
  },
  {
    id: "intermediate-bodyweight-mobility-45",
    title: "Intermediate Bodyweight Mobility Program",
    description:
      "A mobility and control program using bodyweight flows, isometric holds, and active range drills.",
    level: "Intermediate",
    goal: "Mobility",
    equipment: "Bodyweight",
    duration: 45,
    programLength: 6,
    totalExercises: 30,
    recommendedFor: "Active users improving movement quality.",
  },
  {
    id: "intermediate-full-gym-mobility-45",
    title: "Intermediate Full Gym Mobility Support Plan",
    description:
      "A gym-based mobility plan using cables, benches, bands, and light loaded stretches for better training readiness.",
    level: "Intermediate",
    goal: "Mobility",
    equipment: "Full Gym",
    duration: 45,
    programLength: 6,
    totalExercises: 28,
    recommendedFor: "Gym users who want mobility work alongside strength training.",
  },
  {
    id: "advanced-full-gym-fat-loss-75",
    title: "Advanced Full Gym Fat Loss Program",
    description:
      "A demanding gym plan with strength blocks, conditioning intervals, and high-effort finishers for experienced trainees.",
    level: "Advanced",
    goal: "Fat Loss",
    equipment: "Full Gym",
    duration: 75,
    programLength: 10,
    totalExercises: 46,
    recommendedFor: "Experienced gym users with strong recovery habits.",
  },
  {
    id: "advanced-dumbbells-fat-loss-60",
    title: "Advanced Dumbbell Fat Loss Program",
    description:
      "A high-density dumbbell program using complexes, unilateral strength work, and conditioning-focused progressions.",
    level: "Advanced",
    goal: "Fat Loss",
    equipment: "Dumbbells",
    duration: 60,
    programLength: 8,
    totalExercises: 38,
    recommendedFor: "Advanced trainees who need challenging equipment-light sessions.",
  },
  {
    id: "advanced-bodyweight-fat-loss-60",
    title: "Advanced Bodyweight Fat Loss Plan",
    description:
      "A challenging bodyweight plan with high-output intervals, core stamina, and mobility-based recovery blocks.",
    level: "Advanced",
    goal: "Fat Loss",
    equipment: "Bodyweight",
    duration: 60,
    programLength: 8,
    totalExercises: 36,
    recommendedFor: "Experienced users who train without equipment.",
  },
  {
    id: "advanced-full-gym-strength-75",
    title: "Advanced Full Gym Strength Program",
    description:
      "A periodized strength plan centered on heavy compound lifts, targeted accessories, and performance tracking.",
    level: "Advanced",
    goal: "Strength",
    equipment: "Full Gym",
    duration: 75,
    programLength: 12,
    totalExercises: 52,
    recommendedFor: "Advanced lifters pursuing measurable strength progress.",
  },
  {
    id: "advanced-dumbbells-strength-60",
    title: "Advanced Dumbbell Strength Plan",
    description:
      "A demanding dumbbell strength plan featuring unilateral loading, tempo control, and high-tension accessory work.",
    level: "Advanced",
    goal: "Strength",
    equipment: "Dumbbells",
    duration: 60,
    programLength: 10,
    totalExercises: 42,
    recommendedFor: "Advanced users training with limited equipment.",
  },
  {
    id: "advanced-bodyweight-strength-60",
    title: "Advanced Bodyweight Strength Program",
    description:
      "A bodyweight strength program using advanced progressions, holds, tempo work, and strict movement standards.",
    level: "Advanced",
    goal: "Strength",
    equipment: "Bodyweight",
    duration: 60,
    programLength: 10,
    totalExercises: 40,
    recommendedFor: "Experienced calisthenics-focused trainees.",
  },
  {
    id: "advanced-full-gym-muscle-gain-75",
    title: "Advanced Full Gym Muscle Gain Program",
    description:
      "A high-volume hypertrophy plan with advanced exercise selection, intensity techniques, and planned deloads.",
    level: "Advanced",
    goal: "Muscle Gain",
    equipment: "Full Gym",
    duration: 75,
    programLength: 12,
    totalExercises: 56,
    recommendedFor: "Experienced lifters focused on muscle growth.",
  },
  {
    id: "advanced-dumbbells-muscle-gain-60",
    title: "Advanced Dumbbell Muscle Gain Program",
    description:
      "A dumbbell hypertrophy program using mechanical tension, unilateral volume, and controlled fatigue management.",
    level: "Advanced",
    goal: "Muscle Gain",
    equipment: "Dumbbells",
    duration: 60,
    programLength: 10,
    totalExercises: 44,
    recommendedFor: "Advanced home trainees building muscle with dumbbells.",
  },
  {
    id: "advanced-full-gym-conditioning-75",
    title: "Advanced Full Gym Conditioning Program",
    description:
      "A performance-focused conditioning program with intervals, loaded carries, circuits, and structured recovery.",
    level: "Advanced",
    goal: "Conditioning",
    equipment: "Full Gym",
    duration: 75,
    programLength: 10,
    totalExercises: 48,
    recommendedFor: "Advanced users building high work capacity.",
  },
  {
    id: "advanced-at-home-conditioning-60",
    title: "Advanced At Home Conditioning Plan",
    description:
      "A challenging home conditioning plan that uses timed blocks, strength endurance, and recovery-aware pacing.",
    level: "Advanced",
    goal: "Conditioning",
    equipment: "At Home",
    duration: 60,
    programLength: 8,
    totalExercises: 38,
    recommendedFor: "Experienced users training at home.",
  },
  {
    id: "advanced-bodyweight-conditioning-60",
    title: "Advanced Bodyweight Conditioning Program",
    description:
      "An equipment-free conditioning plan using advanced intervals, core strength, and body control progressions.",
    level: "Advanced",
    goal: "Conditioning",
    equipment: "Bodyweight",
    duration: 60,
    programLength: 8,
    totalExercises: 40,
    recommendedFor: "Advanced bodyweight trainees improving stamina.",
  },
  {
    id: "advanced-full-gym-mobility-60",
    title: "Advanced Full Gym Mobility Program",
    description:
      "A gym-supported mobility plan with loaded range work, stability drills, and movement preparation for advanced training.",
    level: "Advanced",
    goal: "Mobility",
    equipment: "Full Gym",
    duration: 60,
    programLength: 8,
    totalExercises: 36,
    recommendedFor: "Advanced lifters who need mobility for performance.",
  },
  {
    id: "advanced-bodyweight-mobility-45",
    title: "Advanced Bodyweight Mobility Flow",
    description:
      "A bodyweight mobility program using active range, controlled transitions, and end-range strength.",
    level: "Advanced",
    goal: "Mobility",
    equipment: "Bodyweight",
    duration: 45,
    programLength: 8,
    totalExercises: 34,
    recommendedFor: "Experienced users improving control and flexibility.",
  },
  {
    id: "advanced-dumbbells-mobility-45",
    title: "Advanced Dumbbell Mobility Support Plan",
    description:
      "A mobility-support plan using light dumbbells for loaded range, stability, and resilient movement patterns.",
    level: "Advanced",
    goal: "Mobility",
    equipment: "Dumbbells",
    duration: 45,
    programLength: 8,
    totalExercises: 34,
    recommendedFor: "Advanced trainees adding mobility to strength-focused weeks.",
  },
  {
    id: "intermediate-at-home-strength-45",
    title: "Intermediate At Home Strength Program",
    description:
      "A practical home strength routine using controlled progressions, stability work, and repeatable weekly structure.",
    level: "Intermediate",
    goal: "Strength",
    equipment: "At Home",
    duration: 45,
    programLength: 8,
    totalExercises: 30,
    recommendedFor: "Users who want strength progress without a gym membership.",
  },
  {
    id: "beginner-full-gym-mobility-45",
    title: "Beginner Full Gym Mobility Plan",
    description:
      "A beginner gym mobility plan using benches, cables, and light machine assistance to improve range of motion.",
    level: "Beginner",
    goal: "Mobility",
    equipment: "Full Gym",
    duration: 45,
    programLength: 4,
    totalExercises: 20,
    recommendedFor: "New gym users who want better movement confidence.",
  },
];

function buildOptions(): WorkoutFilterOptions {
  return {
    levels: LEVELS,
    goals: GOALS,
    equipment: EQUIPMENT,
    durations: DURATIONS,
  };
}

export const getWorkoutRecommendationData = cache(async () => {
  return {
    programs: CURATED_WORKOUT_PROGRAMS,
    options: buildOptions(),
  };
});
